from selenium.webdriver.common.by import By


class ProjectsPageLocators:
    PROJECTS_TAB = (By.XPATH, '//*[@id="root"]/div[2]/div/div[1]/div[2]/div[1]/div[3]/a[2]/div')
    CREATE_PROJECT_BTN = (By.XPATH, '//*[@id="root"]/div[2]/div/div[2]/div[2]/div[2]/div[1]/button')
    CREATE_PROJECT_MODAL = (By.XPATH, '/html/body/div[4]/div[3]/div')
    PROJECT_NAME = (By.ID, 'projectName')
    PROJECT_SHORT_NAME = (By.ID, 'projectShortName')
    CLIENT_FIELD = (By.XPATH, '//*[@id="tags-outlined"]/div')
    SELECT_CLIENT = (By.ID, 'react-select-3-option-0')
    BILLABLE = (By.XPATH, '//*[@id="selectBillable"]/div/div[1]/div[2]')
    ESTIMATED_HOURS = (By.XPATH, '//div[3]/div/div/div/div/div/input')
    ESTIMATED_MINUTES = (By.XPATH, '//*[@id=":r4p:"]')
    MANAGER = (By.XPATH, '//div[3]/div[2]/div/div/div/div')
    SELECT_MANAGER = (By.ID, 'react-select-5-option-2')
    STATUS = (By.XPATH, '//div[2]/div[4]/div/div/div/div/div')
    SELECT_STATUS = (By.ID, 'react-select-6-option-1')
    BUSINESS_UNIT = (By.XPATH, '//div[4]/div[2]/div/div/div/div/input')
    DEFINE_START_CHECKBOX = (By.XPATH, '//div[5]/div/img')
    DEFINE_END_CHECKBOX = (By.XPATH, '//div[5]/div[2]/img')
    PROJECT_COLOR = (By.CSS_SELECTOR, '.project-form__project-color')
    SELECT_PROJECT_COLOR = (By.CSS_SELECTOR, 'span:nth-child(14) > div div')
    PROJECT_NOTES = (By.XPATH, '//div[6]/div/div/div/div[2]/div/div[2]/div/div/div/div')
    ADVANCED_TAB = (By.XPATH, '//div[3]/div/div/div/div[2]/p')
    ADD_TASKS_BTN = (By.XPATH, '//div[3]/div/div/div[2]/div/img')
    TASK_NAME = (By.XPATH, '//div[2]/div[2]/div/div/div/div/input')
    SAVE_TASK_BTN = (By.XPATH, '//div[2]/div[2]/div/div[2]/div/img')
    DELETE_TASK_BTN = (By.XPATH, '//div[2]/div[2]/div/div/div[2]/img')
    CREATE_BTN = (By.XPATH, '//div[2]/button/p')
    SUCCESS_MESSAGE = (By.XPATH, '//body/div/div[2]/div[2]/p')
    SEARCH_FIELD = (By.ID, 'filterProjects')
    SELECT_ALL_PROJECTS = (By.XPATH, '//div[4]/div/div/img')
    PROJECT_RECORD_SELECT = (By.XPATH, "//div[@id='root']/div[2]/div/div[4]/div[2]/div/div/div/img")
    ARCHIVE_PROJECT_BTN = (By.ID, 'deleteProjectPageButton')
    ARCHIVE_PROJECT_MODAL = (By.XPATH, "//img[@id=deleteProjectPageButton']")
    ARCHIVE_PROJECT_BTN_MODAL = (By.XPATH, '//div[2]/button/p')
    FILTER_PROJECTS_BY_ACTIVITY = (By.XPATH, '//div[2]/div/div[2]/div/div[2]/div/div/div')
    SELECT_ARCHIVED_PROJECTS = (By.XPATH, '//div[text()="Archived"]')
    SELECT_ARCHIVED_PROJECT_CHECKBOX = (By.XPATH, "//div[@id='root']/div[2]/div/div[4]/div[2]/div/div/div/img")
    DELETE_ARCHIVED_PROJECT_BTN = (By.ID, 'deleteProjectPageButton')
    DELETE_PROJECT_BTN = (By.XPATH, '//div[2]/button/p')
    PROJECTS_LIST = (By.CLASS_NAME, 'projects-page__project-element')
    ARCHIVED_LIST = (By.CSS_SELECTOR, '#root > div.App > div > div.projects-page__projects-content > '
                                      'div.projects-page__'
                                      'project-list > div:nth-child(1) > div')

    MANAGE_CLIENTS_BTN = (By.XPATH, '//*[@id="root"]/div[2]/div/div[2]/div[2]/div[1]/div')
    NEW_CLIENT_BTN = (By.XPATH, '//*[@id="createClient"]')
    CLIENT_NAME = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/input[1]')
    CLIENT_EMAIL = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/input[2]')
    CLIENT_PHONE = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/input[3]')
    SAVE_CLIENT_BTN = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/div/div[1]')
    CANCEL_CLIENT_CREATION_BTN = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[1]/div/div[2]')
    CLIENT_EDIT_BTN = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[2]/div/div[1]')
    CLIENT_DELETE_BTN = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[2]/div/div[2]')
    SHARE_CLIENT_CALENDAR_BTN = (By.XPATH, '/html/body/div[4]/div[3]/div/div[2]/div[2]/div[2]/div/div[3]')
    CLIENT_CREATED_SUCCESS_MESSAGE = (By.XPATH, '//div[4]/div[3]')
    CLIENT_LIST = (By.CLASS_NAME, 'clients-modal__row')

